# Generated by Django 3.2.6 on 2021-08-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名称', max_length=40)),
                ('link', models.URLField(help_text='项目链接')),
                ('slogan', models.CharField(help_text='标语', max_length=256)),
            ],
            options={
                'verbose_name': '项目',
            },
        ),
    ]
